### PR TITLE
Enable continuous integration with Travis CI

### PR DESCRIPTION
**Pull request by gabrielepmattia**
This PR is for enabling Travis CI to auto-build Fog05. CI will allow understanding if the build process succeeds in a clean environment. This contribution must consist of:
- [x] creating a `build.sh` file for automating the build (copying the instructions from BUILD.md)
- [x] updating the `.travis.yml` file for installing dependencies
- [x] making the build process happen in a Debian docker container (GitLab CI style)

Please do not merge this PR until a successful build is obtained. Build log can be seen [here](https://travis-ci.org/gabrielepmattia/fog05). 

Latest build of the merging branch:

status

### CODE REVIEW

**Comment by gabrielepmattia** [comment]
Hi @gabrik, it seems that [build fails](https://travis-ci.org/gabrielepmattia/fog05) when installing `sdk-ocaml`
```
make -C sdk/sdk-ocaml install
make[1]: Entering directory '/fog05/sdk/sdk-ocaml'
opam install . --working-dir
[WARNING] Running as root is not recommended
fos-sdk is now pinned to git+file:///fog05/sdk/sdk-ocaml#HEAD (version 0.1)
The following dependencies couldn't be met:
  - fos-sdk -> apero-core >= 0.4.6
      no matching version
No solution found, exiting
```

**Comment by gabrielepmattia** [comment]
> Hi @gabrik, it seems that [build fails](https://travis-ci.org/gabrielepmattia/fog05) when installing `sdk-ocaml`
> 
> ```
> make -C sdk/sdk-ocaml install
> make[1]: Entering directory '/fog05/sdk/sdk-ocaml'
> opam install . --working-dir
> [WARNING] Running as root is not recommended
> fos-sdk is now pinned to git+file:///fog05/sdk/sdk-ocaml#HEAD (version 0.1)
> The following dependencies couldn't be met:
>   - fos-sdk -> apero-core >= 0.4.6
>       no matching version
> No solution found, exiting
> ```

Sorry my fault, I did not updated apero dependencies to 0.4.6

**Comment by gabrik** [comment]
Hi @gabrielepmattia,
Thanks for this PR, we already had the travis integration for each component but it was missing on the main repo.

I guess I have to merge it to see if it actually builds right?

**Comment by gabrielepmattia** [comment]
Hi @gabrik, there's no need to merge for seeing if it is building correctly since the build is triggered on my branch https://github.com/gabrielepmattia/fog05/tree/add-ci-script (that is even with master) and the current status can be seen here https://travis-ci.org/gabrielepmattia/fog05 

I would wait to merge until we get a successful build, then I would create a tag with the version (perhaps a beta version, like 0.0.1b), in this way we can create and ship an installable .deb for Debian 10.

Now I'm trying to switch to dune 1.11.4

**Comment by gabrik** [comment]
I was looking at the logs, and It cannot find the build.sh even if it is here. 
My guessing is that it clones a wrong repo/branch

**Comment by gabrielepmattia** [comment]
Yes, because we didn't merged the branches, follow the logs here https://travis-ci.org/gabrielepmattia/fog05

**Comment by gabrielepmattia** [comment]
We still get the same error https://travis-ci.org/gabrielepmattia/fog05/jobs/645485319#L1654 do you mind if we switch to the install command `dune install` instead of `opam install` in [build.sh](https://github.com/gabrielepmattia/fog05/blob/e2a87c2914e308943ce3c70ba4bb85063279cbb0/build.sh)? Otherwise how we can solve this problem?

**Comment by gabrik** [comment]
Hi see, actually, for some reason I can see that when installing `apero-core` dune gets updated https://travis-ci.org/gabrielepmattia/fog05/jobs/645485319#L1535
I guess I can fix it because I have access to that repo.
I'll do that and then I'll update you in this PR.

**Comment by gabrik** [comment]
I have fixed the dependency repository, just restarted the build to check if it works

**Comment by gabrielepmattia** [comment]
So we need to git checkout to master apero-core?

**Comment by gabrik** [comment]
Nope, same tag, I have removed the old tag and created a new one with the fix.

**Comment by gabrielepmattia** [comment]
Perfect

**Comment by gabrielepmattia** [comment]
It seems that apero-core depends on ocaml < 3.07 https://travis-ci.org/gabrielepmattia/fog05/builds/645485318#L1534

**Comment by gabrik** [comment]
My bad, I have done a mistake in the opam file. 
Just fixed it, please retry the build and let me know.

**Comment by gabrielepmattia** [comment]
Okay, but see this issue before https://github.com/eclipse-fog05/api-ocaml/issues/5

**Comment by gabrielepmattia** [comment]
Can you merge [your branch](https://github.com/gabrik/api-ocaml) with https://github.com/eclipse-fog05/api-ocaml since this repo is bound to it

**Comment by gabrik** [comment]
Done! Please let me know if there are any other issue

**Comment by gabrielepmattia** [comment]
Seems that "atdgen" library is missing https://travis-ci.org/gabrielepmattia/fog05/jobs/645850828#L1892

**Comment by gabrik** [comment]
> Seems that "atdgen" library is missing https://travis-ci.org/gabrielepmattia/fog05/jobs/645850828#L1892

I see I have no right to touch that repository, I suggest that for `atdgen` we install it before installing the dependencies. Same for `conf-libev` and `ocp-ocamlres` 

You can just add those to https://github.com/gabrielepmattia/fog05/blob/add-ci-script/.travis.yml#L18 

it would become
```
- docker exec build opam install dune.1.11.4 atdgen.2.0.0 conf-libev  ocp-ocamlres -y
```
Also as you are building in a container with the sandboxing disabled, you can avoid to install `bubblewrap`

**Comment by gabrik** [comment]
I see this: https://travis-ci.org/gabrielepmattia/fog05/builds/646060107#L2531 
Can you try to run that command inside the container before the execution of build.sh?

**Comment by gabrielepmattia** [comment]
Yes, but I see that there is another dependency when installing `z_storage` package https://travis-ci.org/gabrielepmattia/fog05/builds/646060107#L1900

**Comment by gabrik** [comment]
That's not an issue, the `z_storage` is an example package, even if it fails the installation of the other dependencies just works fine.
The only issue I see is that the shell does not find dune.

**Comment by gabrik** [comment]
I'm running the same CI build on a local machine to verify why inside the container it does not find opam.

**Comment by gabrielepmattia** [comment]
Done, I fixed it. The dollar sign gets interpreted outside the container

**Comment by gabrik** [comment]
@gabrielepmattia I tested on a local docker, following as possible the travis CI
I got it working by changing https://github.com/gabrielepmattia/fog05/blob/add-ci-script/.travis.yml#L24 with:
```
- docker exec build bash -c "docker exec build bash -c "eval $(opam env) && cd fog05 && ./build.sh
```

**Comment by gabrik** [comment]
@gabrielepmattia I tested on a local docker, following as possible the travis CI
I got it working by changing https://github.com/gabrielepmattia/fog05/blob/add-ci-script/.travis.yml#L24 with:

```
- docker exec build bash -c "opam env > .opamprofile && source .opamprofile && cd fog05 && ./build.sh"
```

I guess it is worth a try

**Comment by gabrik** [comment]
I see it passing! Congratis @gabrielepmattia

**Comment by gabrielepmattia** [comment]
Perfect, it successfully builds. We can merge this PR or we also want to create a deb package at the end of the building phase?

**Comment by gabrik** [comment]
I can merge it.
Regarding the deb package, It would be nice to have them, but it is worth knowing that a postinst script is required and we cannot have only one single deb.

Ideally we should have something the one hand-crafted in this repo: https://github.com/atolab/fog05_debs

In this case, I guess that the agent+yaks+linux_plugin one can be done in this repo, while the other ones should be built by the CI of the other repositories.

This means that I will update the other repositories to have a CI that follows the one of this repo,

**Comment by gabrielepmattia** [comment]
Perfect! Congrats even to you!

Before merging I would make other edits:
* [ ] in BUILD.md we can tell to run build.sh
* [ ] I would move the installation of dune, atdgen and other missing libraries in build.sh since they are susciptible to change

For debs I would open another PR, and in this repo I would build only the agent since other components like yaks and linux_plugin have different repository and they can be updated independently from the fog05 agent, I guess

After these changes and this merge you can create a tag with the latest version of the agent, so we have a checkpoint

**Comment by gabrik** [comment]
@gabrielepmattia please ping me when I can merge this

**Comment by gabrielepmattia** [comment]
Done, I think we are ready to merge

**Comment by gabrik** [comment]
@gabrielepmattia I have just created a pre-release tag `v0.1.0.pre-release` that can be used if you want to go ahead with the build of deb packages.

**Pull request merged**
